"""FastAPI entry point for the Policy Response Analyser backend."""
import asyncio
import os
import sys
import time
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from backend.core.state import pipeline, SEMANTIC_AVAILABLE
from backend.core.logger import log as app_log
from backend.routes import search, pipeline as pipeline_route, log, preview

# Log local runtime mode clearly at startup.
if SEMANTIC_AVAILABLE:
    print("[STARTUP] mode=full | semantic search enabled", file=sys.stderr, flush=True)
else:
    print(
        "[STARTUP] mode=lightweight | reproducible TF-IDF baseline active | "
        "full semantic/hybrid mode available when optional dependencies are loaded",
        file=sys.stderr,
        flush=True,
    )


@asynccontextmanager
async def lifespan(_app: FastAPI):
    """Load the prebuilt search corpus from disk so startup completes quickly.

    The prebuilt corpus is generated by ``scripts/precompute_search_corpus.py``
    and committed to the repo.  Loading pickled chunks is cheap (milliseconds),
    avoiding unnecessary PDF-processing work during backend startup.

    Strategy:
    1. Try ``load_prebuilt_corpus()`` — fast disk load, no PDF rebuilding.
    2. If the prebuilt corpus is missing or invalid, log a clear warning and
       yield immediately.  The search-route safety net (``_ensure_default_search_corpus_loaded``)
       will rebuild lazily on the first user query instead.

    Embeddings stay lazy (built on the first Hybrid/Semantic query per preset)
    to keep cold-start time bounded regardless of corpus origin.
    """
    print("[STARTUP] loading prebuilt search corpus from disk...", file=sys.stderr, flush=True)
    app_log.emit("startup.preload", "loading prebuilt search corpus", "info")
    t0 = time.monotonic()
    try:
        pairs_loaded, chunks_loaded = await asyncio.to_thread(
            pipeline.load_prebuilt_corpus
        )
        ms = int((time.monotonic() - t0) * 1000)
        if pairs_loaded == 0 and pipeline.preset_cache:
            total_chunks = sum(
                len(s.policy_chunks) + len(s.response_chunks)
                for s in pipeline.preset_cache.values()
            )
            print(
                f"[STARTUP] prebuilt corpus: already cached "
                f"{len(pipeline.preset_cache)} pairs, {total_chunks} chunks "
                f"({ms} ms)",
                file=sys.stderr,
                flush=True,
            )
            app_log.emit(
                "startup.preload",
                f"already cached: {len(pipeline.preset_cache)} pairs, "
                f"{total_chunks} chunks",
                "ok",
                ms=ms,
            )
        else:
            print(
                f"[STARTUP] prebuilt corpus loaded: {pairs_loaded} pairs, "
                f"{chunks_loaded} chunks ({ms} ms)",
                file=sys.stderr,
                flush=True,
            )
            app_log.emit(
                "startup.preload",
                f"prebuilt corpus loaded: {pairs_loaded} pairs, "
                f"{chunks_loaded} chunks",
                "ok",
                ms=ms,
            )
    except FileNotFoundError as exc:
        ms = int((time.monotonic() - t0) * 1000)
        print(
            f"[STARTUP] prebuilt corpus not found — search will be built "
            f"lazily on first request ({exc}) ({ms} ms)",
            file=sys.stderr,
            flush=True,
        )
        app_log.emit(
            "startup.preload",
            "prebuilt corpus missing; lazy loading enabled",
            "warn",
        )
    except Exception as exc:
        ms = int((time.monotonic() - t0) * 1000)
        print(
            f"[STARTUP] prebuilt corpus load FAILED ({type(exc).__name__}: "
            f"{exc}); search will be built lazily on first request ({ms} ms)",
            file=sys.stderr,
            flush=True,
        )
        app_log.emit(
            "startup.preload",
            f"prebuilt corpus failed ({type(exc).__name__}: {exc}); "
            f"lazy loading enabled",
            "err",
        )
    yield


app = FastAPI(title="Policy Response Analyser API", lifespan=lifespan)

# ---------------------------------------------------------------------------
# CORS — explicit origins so preflight OPTIONS requests succeed for every
# allowed caller. The optional frontend is expected to run from local Vite
# dev-server origins. Extra local origins can be supplied via
# CORS_ALLOWED_ORIGINS or the legacy CORS_ORIGINS variable as a comma-separated
# list.
# ---------------------------------------------------------------------------
_DEFAULT_ORIGINS: list[str] = [
    # Local Vite dev servers
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:3000",
]


def _parse_origins_env(*var_names: str) -> list[str]:
    for name in var_names:
        raw = os.environ.get(name, "")
        parsed = [o.strip() for o in raw.split(",") if o.strip()]
        if parsed:
            return parsed
    return []


_extra_origins = _parse_origins_env("CORS_ALLOWED_ORIGINS", "CORS_ORIGINS")
_origins: list[str] = list(dict.fromkeys(_DEFAULT_ORIGINS + _extra_origins))

# Log at import time so local startup output confirms which origins are
# allowed before the first request arrives.
print(
    f"[CORS] allowed origins ({len(_origins)}): {_origins}",
    file=sys.stderr,
    flush=True,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_origins,
    allow_credentials=False,          # no cookies/auth headers needed
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type", "Authorization", "Accept"],
)

app.include_router(pipeline_route.router, prefix="/api/pipeline", tags=["pipeline"])
app.include_router(search.router,         prefix="/api/search",   tags=["search"])
app.include_router(preview.router,        prefix="/api/preview",  tags=["preview"])
app.include_router(log.router,            prefix="/api/log",      tags=["log"])


@app.get("/health")
@app.get("/api/health")
def health():
    return {"status": "ok"}
